windowrulev2 = supress_event maximize, match:class:.*
windowrulev2 = \
  match:class:^$, \
  match:title:^$, \
  match:xwayland:1, \
  match:floating:1, \
  match:fullscreen:0, \
  match:pinned:0, \
  no_initial_focus:1
windowrulev2 = tile:1, match:class:.*

workspace = 10, name:0
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 0, monitor:eDP-1
