font_family      JetBrains Mono Nerd Font
font_size        9.0
include nord.conf

cursor_shape block
cursor_trail 8
cursor_trail_start_threshold 0
cursor_trail_decay 0.05 0.15
shell_integration no-cursor

window_title_template kitty
dynamic_background_opacity yes
hide_window_decorations yes
window_padding_width 0
window_padding_height 0

background_opacity 0.9
set_background_opacity 1

scrollback_lines 10000

middle_click_paste yes
enable_kitty_graphics yes
enable_audio_bell no
