binds {
    pass_mouse_when_bound = false
        scroll_event_delay = 0

        drag_threshold = 0

        workspace_back_and_forth = false
        hide_special_on_workspace_change = true
        allow_workspace_cycles = false
        workspace_center_on = 0

        focus_preferred_method = 0
        movefocus_cycles_fullscreen = false
        movefocus_cycles_groupfirst = false
        window_direction_monitor_fallback = true

        ignore_group_lock = false

        disable_keybind_grabbing = false
        allow_pin_fullscreen = false
}

bind = $mainMod, Q, exec, $terminal
bind = $mainMod SHIFT, Q, exec, [float; size 1400 900; center] $terminal

bind = $mainMod, C, killactive

bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, W, exec, $browser

bind = $mainMod, T, togglesplit
bind = $mainMod, Y, togglefloating
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0

workspace = 10, name:0

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

bind = $mainMod CTRL, l, resizeactive, 50 0
bind = $mainMod CTRL, h, resizeactive, -50 0
bind = $mainMod CTRL, k, resizeactive, 0 -50
bind = $mainMod CTRL, j, resizeactive, 0 50

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, name:0

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, name:0

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
bind = $mainMod ALT, S, movetoworkspacesilent, special:magic

bind = $mainMod SHIFT, Tab, workspace, -1
bind = $mainMod, Tab, workspace, +1

bind = $mainMod + Ctrl, Tab, movetoworkspace, r+1
bind = $mainMod + Shift + Ctrl, Tab, movetoworkspace, r-1

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = , Print, exec, grim -g "$(slurp)" ~/Downloads/screenshot-area-$(date +'%Y%m%d-%H%M%S').png && wl-copy < ~/Downloads/screenshot-area-$(date +'%Y%m%d-%H%M%S').png
bind = SHIFT, Print, exec, grim ~/Downloads/screenshot-full-$(date +'%Y%m%d-%H%M%S').png && wl-copy < ~/Downloads/screenshot-full-$(date +'%Y%m%d-%H%M%S').png

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause

bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
