vim.keymap.set( 'n','<c-h>',  ':wincmd h<CR>')
vim.keymap.set( 'n','<c-j>',  ':wincmd j<CR>')
vim.keymap.set( 'n','<c-k>',  ':wincmd k<CR>')
vim.keymap.set( 'n','<c-l>',  ':wincmd l<CR>')
vim.keymap.set( 'n','<c-d>','<c-d>zz')
vim.keymap.set( 'n','<c-u>','<c-u>zz')
vim.keymap.set( 'n', 'n','nzzzv')
vim.keymap.set( 'n', 'N','Nzzzv')
