vim.keymap.set( 'n', '<C-h>', ':wincmd h<CR>')
vim.keymap.set( 'n', '<C-j>', ':wincmd j<CR>')
vim.keymap.set( 'n', '<C-k>', ':wincmd k<CR>')
vim.keymap.set( 'n', '<C-l>', ':wincmd l<CR>')
vim.keymap.set( 'n', '<C-d>', '<c-d>zz')
vim.keymap.set( 'n', '<C-u>', '<c-u>zz')
vim.keymap.set( 'n', 'n', 'nzzzv')
vim.keymap.set( 'n', 'N', 'Nzzzv')
